twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["form/bootstrap_4_layout.html.twig", "bootstrap_4_layout.html.twig"]
  globals:
    locales: '@App\Tools\Twig\LocalLanguages'
    url_manager: '@App\Tools\Request\UrlSessionManager'
    constants: '@App\Tools\AppConstants'
